global:
  listenAddr: ":5555"
  logging: "debug" # panic,fatal,warm,info,debug,trace
  metricsAddr: ":9090"

beacon:
  upstreams:
  - name: remote
    address: http://localhost:5052
    timeoutSeconds: 30
    dataProvider: true