global:
  listenAddr: ":5555"
  logging: "debug" # panic,fatal,warm,info,debug,trace
  metricsAddr: ":9090"

checkpointz:
  caches:
    blocks:
      max_items: 200
    states:
      max_items: 5
  historical_epoch_count: 20
  
beacon:
  upstreams:
  - name: remote
    address: http://localhost:5052
    timeoutSeconds: 30
    dataProvider: true