name: Integration test
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  run-test:
    strategy:
      fail-fast: false
      matrix:
        consensus: [teku]
        network: [sepolia]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - name: Print details
        run: |
          echo "Consensus: ${{ matrix.consensus }}"
          echo "Network: ${{ matrix.network }}"
      - name: Run ${{ inputs.network }}-${{ inputs.consensus }}
        id: run-test
        uses: ./.github/actions/checkpoint-sync
        with:
          ## Variables
          consensus: ${{ matrix.consensus }}
          network: ${{ matrix.network }}